export {default as Home} from './Home/index'
export {default as ListAJobs} from './ListAJobs/index'
export {default as Applications} from './Applications'
export {default as SingleJob} from './SingleJob'
export {default as Accept} from './Accept_Applications'
export {default as Reject} from './Reject_applications'
export {default as ApplicationByPost} from './Application_ByPost'